FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Disable ESLint during build
ENV NEXT_DISABLE_ESLINT=true

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "dev"]
